In [8]:
from os.path import join, expanduser
import numpy as np
import xarray as xr

In [2]:
filename = expanduser(join("~", "Downloads", "EMIT_L2A_RFL_001_20240521T232728_2414216_003.nc"))

In [3]:
ds = xr.open_dataset(filename)
ds

<xarray.Dataset> Size: 2GB
Dimensions:      (downtrack: 1280, crosstrack: 1242, bands: 285)
Dimensions without coordinates: downtrack, crosstrack, bands
Data variables:
    reflectance  (downtrack, crosstrack, bands) float32 2GB ...
Attributes: (12/38)
    ncei_template_version:             NCEI_NetCDF_Swath_Template_v2.0
    summary:                           The Earth Surface Mineral Dust Source ...
    keywords:                          Imaging Spectroscopy, minerals, EMIT, ...
    Conventions:                       CF-1.63
    sensor:                            EMIT (Earth Surface Mineral Dust Sourc...
    instrument:                        EMIT
    ...                                ...
    southernmost_latitude:             32.925119340889395
    spatialResolution:                 0.000542232520256367
    spatial_ref:                       GEOGCS["WGS 84",DATUM["WGS_1984",SPHER...
    geotransform:                      [-1.16103646e+02  5.42232520e-04 -0.00...
    day_night_flag:                    Day
    title:                             EMIT L2A Estimated Surface Reflectance...

In [4]:
ds.dims

FrozenMappingWarningOnValuesAccess({'downtrack': 1280, 'crosstrack': 1242, 'bands': 285})

In [6]:
loc = xr.open_dataset(filename, group="location")
loc

<xarray.Dataset> Size: 109MB
Dimensions:  (downtrack: 1280, crosstrack: 1242, ortho_y: 1893, ortho_x: 2327)
Dimensions without coordinates: downtrack, crosstrack, ortho_y, ortho_x
Data variables:
    lon      (downtrack, crosstrack) float64 13MB ...
    lat      (downtrack, crosstrack) float64 13MB ...
    elev     (downtrack, crosstrack) float64 13MB ...
    glt_x    (ortho_y, ortho_x) float64 35MB ...
    glt_y    (ortho_y, ortho_x) float64 35MB ...

In [7]:
loc["glt_x"]

<xarray.DataArray 'glt_x' (ortho_y: 1893, ortho_x: 2327)> Size: 35MB
[4405011 values with dtype=float64]
Dimensions without coordinates: ortho_y, ortho_x
Attributes:
    long_name:  GLT Sample Lookup
    units:      pixel location

In [9]:
reflectance = np.array(ds["reflectance"])
reflectance

array([[[0.04310642, 0.04336452, 0.04150592, ..., 0.10212765,
         0.0974834 , 0.09012822],
        [0.06145171, 0.06501866, 0.06859049, ..., 0.10978349,
         0.10137388, 0.09884916],
        [0.06124046, 0.0649093 , 0.0685825 , ..., 0.10782409,
         0.09501854, 0.0907679 ],
        ...,
        [0.00507217, 0.00802279, 0.01125222, ..., 0.1837036 ,
         0.18001686, 0.17860676],
        [0.0060593 , 0.00890038, 0.00998863, ..., 0.19765685,
         0.19258572, 0.18802734],
        [0.01689515, 0.01768825, 0.01971469, ..., 0.18779285,
         0.17850284, 0.17630193]],

       [[0.05653568, 0.06005755, 0.06357399, ..., 0.10565821,
         0.10205421, 0.09661389],
        [0.06207323, 0.06573673, 0.0694032 , ..., 0.10960843,
         0.09955885, 0.09995052],
        [0.06266887, 0.06635007, 0.07002756, ..., 0.12251341,
         0.10631712, 0.10210592],
        ...,
        [0.0090206 , 0.01041509, 0.01469167, ..., 0.19406983,
         0.18753886, 0.18678044],
        [0.0

In [10]:
glt_x = np.array(loc["glt_x"])
glt_x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
glt_y = np.array(loc["glt_y"])
glt_y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])